Mm 394 Implement unit tests for MailService
ong-bitcoin-argentina/DIDI-SSI-Server pull request #136
Opened 2021-06-10 21:29 UTC by lucas-mauro

Mm 394 Implement unit tests for MailService

2021-06-15 16:09 UTC, MatiasOS requested changes

2021-06-15 16:09 UTC, MatiasOS commented on __tests__/services/Mail/constants.js
> +  appData: {
Acá estamos con una verificación de mail. Capaz debería llamarse  verificationData no?

2021-06-15 16:09 UTC, MatiasOS commented on __tests__/services/Mail/getByMail.test.js
> +});
Agregá otro caso con un mail válido, pero que no está en la db

2021-06-15 16:09 UTC, MatiasOS commented on __tests__/services/Mail/getByMail.test.js
> +    expect(getByEmailResponse).not.toBeNull();
compará que los campos (mail, code, did, etc) que te devuleve sean los esperados

2021-06-15 16:09 UTC, MatiasOS commented on __tests__/services/Mail/isValid.test.js
> +describe('Should be green', () => {
Cambiar al nombre del archivo que se está testeando

2021-06-15 16:09 UTC, MatiasOS commented on __tests__/services/Mail/isValidated.test.js
> +describe('Should be green', () => {
Acá también cambiar el nombre

2021-06-15 19:57 UTC, lucas-mauro commented on __tests__/services/Mail/getByMail.test.js
> +    expect(getByEmailResponse).not.toBeNull();
aca no pude comparar porque al encriptarlo el resultado siempre va a ser distinto

2021-06-15 21:16 UTC, fedelmar commented on __tests__/services/Mail/sendValidationCode.test.js
> +describe('services/Mail/sendValidationCode.test.js', () => {
Hay que hacer un mock de la función para evitar que mande el mail con el código.

2021-06-22 13:17 UTC, fedelmar approved these changes

2021-06-22 14:13 UTC, MatiasOS approved these changes

2021-06-22 14:13 UTC, merged