Mm 400 - Mouro unit tests
ong-bitcoin-argentina/DIDI-SSI-Server pull request #160
Opened 2021-07-08 21:28 UTC by lucas-mauro

Mouro unit tests

2021-07-14 21:59 UTC, MatiasOS requested changes

2021-07-14 21:59 UTC, MatiasOS commented on .travis.yml
> +    secure: BkmggZuzZmG8dczAu/6iNXt5n09tyOk6OPLSePmxXpGoeR/EfpH3WiGzGkfCmD60/w+ocutPn3iS2P1Pl77s2BVEZAeYP/rf4ZTxugX9TMg6h4BKYjeTtY/Nfo5nrGzSgI1oSJUdu3WYyhcOuDoIw6XTN5rA3rUExhxDJRLgL2hnyhe3qQcuOZ+JgFL
Tenés que usar **travis encrypt-file** en lugar de **travis encrypt**

2021-07-15 12:35 UTC, fedelmar commented on .travis.yml
> +    secure: BkmggZuzZmG8dczAu/6iNXt5n09tyOk6OPLSePmxXpGoeR/EfpH3WiGzGkfCmD60/w+ocutPn3iS2P1Pl77s2BVEZAeYP/rf4ZTxugX9TMg6h4BKYjeTtY/Nfo5nrGzSgI1oSJUdu3WYyhcOuDoIw6XTN5rA3rUExhxDJRLgL2hnyhe3qQcuOZ+JgFL
:thumbsup:

2021-07-15 12:51 UTC, MatiasOS approved these changes
lgtm

2021-07-15 12:51 UTC, merged