[WIP]MM-397 Testing Service - CertService
ong-bitcoin-argentina/DIDI-SSI-Server pull request #167
Opened 2021-07-19 18:36 UTC by fedelmar

Tests de los servicios de CertService

2021-07-21 12:18 UTC, Diegoro21 approved these changes, later dismissed

2021-07-22 00:13 UTC, MatiasOS requested changes
Además, se debe testear en general que los servicios lancen error cundo los datos son inválidos, por ejemplo un test que espere que se produzca un error de **Messages.CERTIFICATE.ERR.CREATE**

2021-07-22 00:13 UTC, MatiasOS commented on __tests__/services/Cert/constant.js
> +  algo: {
algo?

2021-07-22 00:13 UTC, MatiasOS commented on __tests__/services/Cert/createCertificate.test.js
> +  test('Expect createCertificate to success', async () => {
Agregá:
- Un test con expDate undefined que funcione
- Un test con expDate que no tenga sentido

2021-07-22 00:13 UTC, MatiasOS commented on __tests__/services/Cert/verifyCertificate.test.js
> +  test('Expect verifyCertificate to success', async () => {
Agregar:
- que falle l verificaciones porque el certificado es invalido
- que falle por la firma
- que pase con un hash

2021-07-22 00:13 UTC, MatiasOS commented on __tests__/services/Cert/verifyCertificateEmail.test.js
> +  test('Expect verifyCertificateEmail to success', async () => {
Probar tambien con una credencial que no sea de mail

2021-07-22 00:13 UTC, MatiasOS commented on __tests__/services/Cert/verifyCertificatePhoneNumber.test.js
> +  test('Expect verifyCertificatePhoneNumber to success', async () => {
Probar con una credencial que nosea de número de telefono

2021-07-22 20:30 UTC, fedelmar commented on __tests__/services/Cert/constant.js
> +  algo: {
Quedo de commits anteriores

2021-08-02 11:15 UTC, MatiasOS requested changes

2021-08-02 11:15 UTC, MatiasOS commented on __tests__/services/Cert/verifyIssuer.test.js
> +      expect(e).toMatch(Messages.ISSUER.ERR.IS_INVALID);
Acá faltó el **code**
expect(e **.code** ).toMatch(Messages.ISSUER.ERR.IS_INVALID);

2021-08-06 14:49 UTC, MatiasOS approved these changes
lgtm

2021-08-06 16:51 UTC, merged