MM 399 -  IssuerService Tests
ong-bitcoin-argentina/DIDI-SSI-Server pull request #169
Opened 2021-07-22 13:21 UTC by fedelmar

Tests para los servicios se Issuer

2021-07-22 16:07 UTC, MatiasOS requested changes, later dismissed
Los errores son los mismos que se repiten en casi todos los tests. Dejé el comment en uno, pero hay que cambiar todas las ocurrencias. 
Para los próximos pr, considerá no incluir cambios que no sean relacionados. Por ejemplo este PR es para los test de issuer service, pero también haces fixes en otros tests (sms, mail). Es mejor hacer otro pr.

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Issuer/callback.test.js
> +    await fetch(`${callbackUrl}/${rskDid}`, deleteOptionsAuth(token, {}));
Realizar un mock para estos llamados. Esto permite además testear casos cuando no responde el callback es incorrecto.

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Issuer/createDelegateTransaction.test.js
> +        await createDelegateTransaction({
Utilizar la forma corta para los objetos. Por ejemplo:
```javascript
await createDelegateTransaction({name, callbackUrl, token, action})
```

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Issuer/addIssuer.test.js
> +  describe('Should be green', () => {
Remover **describe('Should be green', () => {**

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Issuer/createDelegateTransaction.test.js
> +    test('Expect createDelegateTransaction to throw on missing data', async () => {
No hace lo que dice

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Issuer/callback.test.js
> +    test('Expect callback to throw on missing data', async () => {
No hace lo que dice

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Issuer/addIssuer.test.js
> +    test('Expect addIssuer to success', async () => {
Comprobar otros campos además del did

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Issuer/editName.test.js
> +      const issuer = await getIssuerByDID(did);
Revisar la respuesta de `await editName(did, secondName)` en caso de que devuelva un instancia de Issuer

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Issuer/refresh.test.js
> +      expect(response.expireOn).not.toBe(null);
Antes del refresh expireOn es null?

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Issuer/refresh.test.js
> +    test('Expect refresh to throw error on invalid did', async () => {
secondDid no es invalido, en todo caso no está registrado como issuer

2021-07-22 16:07 UTC, MatiasOS commented on __tests__/services/Mail/create.test.js
> +    expect(Object.prototype.toString.call(createRessult.code.hash) === '[object String]')
Estos expect son medio raros. Qué significan? Parece un copy&paste de la primer respuesta de stackoverflow :joy:

2021-07-22 20:27 UTC, fedelmar commented on __tests__/services/Mail/create.test.js
> +    expect(Object.prototype.toString.call(createRessult.code.hash) === '[object String]')
De esta me salvo, https://github.com/ong-bitcoin-argentina/DIDI-SSI-Server/pull/169/commits/029d1414797c513b10e43b18e12990e0086ff14c

2021-07-23 13:54 UTC, fedelmar commented on __tests__/services/Issuer/refresh.test.js
> +      expect(response.expireOn).not.toBe(null);
No, debería compararlos los campos de antes y después entre si.

2021-08-05 14:49 UTC, Diegoro21 approved these changes

2021-08-05 15:03 UTC, merged