MM-448 Nuevo endpoint /issuer/:did/image
ong-bitcoin-argentina/DIDI-SSI-Server pull request #178
Opened 2021-08-06 19:05 UTC by fedelmar

- Se agrega la nueva ruta /issuer/:did/image a Issuer Routes, que devuelve la url de la imagen de un issuer según su Did.
- Se elimina del controlador readIssuerByDid un llamado innecesario a la función getImageUrl.

2021-08-06 20:18 UTC, MatiasOS requested changes, later dismissed

2021-08-06 20:18 UTC, MatiasOS commented on controllers/issuer/index.js
> +const { readIssuerImageByDid } = require('./readIssuerImageByDid');
Como es un array, debería ser images en plural -> readIssuerImage**s**ByDid

2021-08-09 12:21 UTC, Diegoro21 commented on controllers/issuer/readIssuerImagesByDid.js
> +    return ResponseHandler.sendRes(res, [imageUrl]);
En la app se obtiene la imagen desde el imageId, podrias retornar eso tmb?

2021-08-09 13:58 UTC, fedelmar commented on controllers/issuer/readIssuerImagesByDid.js
> +    return ResponseHandler.sendRes(res, [imageUrl]);
sisi

2021-08-09 15:36 UTC, Diegoro21 approved these changes

2021-08-09 16:10 UTC, merged