[WIP] [MM-512] Reemplazar las librerias de Uport
ong-bitcoin-argentina/DIDI-SSI-Server pull request #190
Opened 2021-10-04 15:41 UTC by fedelmar

- Se reemplazan las librerías de uport utilizadas para el manejo de credenciales y emisores, reemplazándolas por métodos creados la librería BlockchainManager.

2021-10-06 15:21 UTC, MatiasOS requested changes

2021-10-06 15:21 UTC, MatiasOS commented on __tests__/services/Blockchain/addDelegate.test.js
> +    expect(result.some((response) => response.status === 'fulfilled'));
Asegurarse que el fulfilled es en la red de RSK

2021-10-06 15:21 UTC, MatiasOS commented on __tests__/services/Blockchain/addDelegate.test.js
> +    expect(result.some((response) => response.status === 'fulfilled'));
Asegurarse que el fulfilled es en la red de LACChain

2021-10-06 15:21 UTC, MatiasOS commented on __tests__/services/Blockchain/addDelegate.test.js
> +    expect(result.some((response) => response.status === 'fulfilled'));
Asegurarse que el fulfilled es en la red de BFA

2021-10-06 15:21 UTC, MatiasOS commented on __tests__/services/Cert/createCertificate.test.js
> +    const expDate = 1;
La línea anterior dice 
test('Expect createCertificate to create certificate with "exp": "0"', async () => {

2021-10-06 15:21 UTC, MatiasOS commented on __tests__/services/Token/constants.js
> +  const jwt = await BlockchainService.createJWT(issuerDID, privateKey, {
No es necesario el destructuring y luego guardarlo en un objeto para payload
 ` const jwt = await BlockchainService.createJWT(issuerDID, privateKey, payload );`

2021-10-06 15:21 UTC, MatiasOS commented on __tests__/services/Token/getPayload.test.js
> +    expect(result.iss).toBe(dataResponse.issuer);
Qué pasó acá que sacaste el sub y el iat?

2021-10-06 15:21 UTC, MatiasOS commented on __tests__/services/Token/getTokenData.test.js
> +    expect(result.payload.iss).toBe(dataResponse.issuer);
Acá por què sacaste el iat y sub?

2021-10-06 15:21 UTC, MatiasOS commented on __tests__/services/Token/verifyToken.test.js
>      const result = await verifyToken(await token);
iat y sub?

2021-10-06 15:21 UTC, MatiasOS commented on services/CertService.js
> +    const credentials = BlockchainService.createVerifiableCredential(
Agregar test para este bloque de código,  parece ser bastante distinto. BlockchainManager.createCertificate() hace mucho más cosas que las que había antes de las modificaciones

2021-10-06 15:21 UTC, MatiasOS commented on services/CertService.js
> +  const token = await BlockchainService.createJWT(
Crear tests para este bloque de código también

2021-10-06 15:21 UTC, MatiasOS commented on services/TokenService.js
> +const BlockchainService = require('./BlockchainService');
Utilizar un solo require para BlockchainService

2021-10-06 15:37 UTC, fedelmar commented on __tests__/services/Token/getTokenData.test.js
> +    expect(result.payload.iss).toBe(dataResponse.issuer);
Porque el blockchain manager los genera automaticamente, y antes lo estaba harcodeando en el token

2021-10-06 19:14 UTC, fedelmar commented on __tests__/services/Cert/createCertificate.test.js
> +    const expDate = 1;
En la librería divide la fecha que le pasas sobre 1000, entonces cualquier numero que le pases menor a 1000 queda el exp en 0. Si le pasas exp en 0, crea la credencial sin expiracion. Deberiamos revisar el funcionamiento en el BlockchainManager

2021-10-12 19:30 UTC, MatiasOS requested changes
Revisar las comparaciones de did, utilizar el método de blockchain manager https://github.com/ong-bitcoin-argentina/DIDI-SSI-Blockchain-manager/blob/develop/src/BlockchainManager.ts#L176

2021-10-12 19:30 UTC, MatiasOS commented on services/BlockchainService.js
> +module.exports.getDidAddress = function getDidAddress(did) {
Por què no https://github.com/ong-bitcoin-argentina/DIDI-SSI-Blockchain-manager/blob/develop/src/BlockchainManager.ts#L145 ?

2021-10-12 19:30 UTC, MatiasOS commented on services/CertService.js
> +    const credentials = BlockchainService.createVerifiableCredential(
Esto sigue siendo diferente

2021-10-12 19:30 UTC, MatiasOS commented on services/CertService.js
> +  if (issuerDid === serverDid) {
Usar https://github.com/ong-bitcoin-argentina/DIDI-SSI-Blockchain-manager/blob/develop/src/BlockchainManager.ts#L176 para las comparaciones

2021-10-12 21:08 UTC, fedelmar commented on services/BlockchainService.js
> +module.exports.getDidAddress = function getDidAddress(did) {
Lo probe y me dice que no existe la funcion, sera por como esta exportada?

2021-10-12 21:44 UTC, fedelmar commented on services/CertService.js
> +    const credentials = BlockchainService.createVerifiableCredential(
Lo reviso, pero como resultado entiendo que devuelven el mismo JWT

2021-10-12 21:54 UTC, fedelmar commented on services/CertService.js
> +    const credentials = BlockchainService.createVerifiableCredential(
Fue en el issuer-module que lo habia comprobado, ahi lo arreglo y subo los cmabios

2021-10-12 22:31 UTC, fedelmar commented on services/CertService.js
> +  if (issuerDid === serverDid) {
lo mismo que para getDidAddress, debera ser modificada desde la libreria para poder utilizarla

2021-10-13 02:06 UTC, MatiasOS requested changes
Parece que esto debería resolver la verificación de issues con multiblockchain. Actualizà la versiòn del blockchain manager y ya estariamos para probar en qa

2021-10-13 02:06 UTC, MatiasOS commented on package.json
> +		"@proyecto-didi/didi-blockchain-manager": "^2.0.0-rc.2",
Porfa, actaulizá a 2.0.0-rc.3

2021-10-13 14:31 UTC, fedelmar commented on package.json
> +		"@proyecto-didi/didi-blockchain-manager": "^2.0.0-rc.2",
listo!

2021-10-13 23:09 UTC, Diegoro21 submitted a review, later dismissed

2021-10-14 22:15 UTC, MatiasOS requested changes

2021-10-14 22:15 UTC, MatiasOS commented on services/IssuerService.js
> +  if (transactions.length > 1) {
No usar if. 
Se mejor la legibilidad haciendo
```javascript
let tx = transactions.find((response) => response.status === 'fulfilled');
```

Pero de todas formas, creo qu sería mejor guardar la lista de transacciones
```javascript
 const delegationHashes = transactions.filter(({status}) => status === 'fulfilled')
      .map(({network, value})=>({network, transactionHash: value.transactionHash}))

...

Issuer.create({
    name, did, expireOn, delegationHashes, description, imageUrl,
});
```

2021-10-15 15:38 UTC, MatiasOS approved these changes
:+1:

2021-10-15 15:38 UTC, merged