[WIP] fix:add-shareRequest-to-issuer
ong-bitcoin-argentina/DIDI-SSI-Server pull request #202
Opened 2021-12-03 21:09 UTC by fedelmar

- Se elimina la red de los dids para buscar en la base de datos de didi server

2021-12-10 12:31 UTC, MatiasOS requested changes

2021-12-10 12:31 UTC, MatiasOS commented on services/IssuerService.js
> + */
Obtiene un shareRequest a partir de un id

2021-12-10 14:30 UTC, MatiasOS submitted a review, later dismissed
:+1:

2021-12-10 15:16 UTC, DoloresGarciaE approved these changes, later dismissed

2021-12-17 18:31 UTC, MatiasOS approved these changes

2021-12-17 18:32 UTC, merged