feature/ME-10-validate-share-request
ong-bitcoin-argentina/DIDI-SSI-Server pull request #215
Opened 2022-05-06 14:36 UTC by SantiagoMaresca

Se agregaron los siguientes middlewares para validar share request:
- validate issuer middleware
- validate schema middleware

Se ejecuto run linter

**El PR esta pendiente de la tarea: ME-50 (Ya que para que la validacion del schema funcione correctamente, se deberia publicar una nueva version del schema del share req en el  vc validator o buscar una solucion alternativa )**

2022-05-11 14:39 UTC, MatiasOS requested changes
Agregar unos tests para los middlewares también y estamos :)

2022-05-11 14:39 UTC, MatiasOS commented on middlewares/ValidateSchema.js
> +      // eslint-disable-next-line max-len
Mejor usar if (...) { 
}
y no deshabilitamos la relga del linter

2022-05-11 14:39 UTC, MatiasOS commented on middlewares/ValidateSchema.js
> +    const { type } = await getPayload(jwt);
Acá hay que usar otra cosa, porque esto utiliza decode que no verifica la firma. Un atacante podría usar un token con un iss modificado.
https://github.com/ong-bitcoin-argentina/DIDI-SSI-Server/blob/develop/services/BlockchainService.js#L117

Este puede ser un buen método, si no hace la verificación contra blockchian
https://github.com/ong-bitcoin-argentina/DIDI-SSI-Server/blob/develop/services/BlockchainService.js#L137

2022-05-11 16:10 UTC, SantiagoMaresca commented
@MatiasOS quedaron subidos los fixes que me comentaste!

2022-05-30 16:38 UTC, claudio-uslenghi commented on __tests__/middlewares/constants.js
> +        issuers: [
Hay que cambarlo issuers a iss

2022-05-30 16:46 UTC, SantiagoMaresca commented on __tests__/middlewares/constants.js
> +        issuers: [
enrealidad este PR es anterior y no incluye el cambio de issuers a `iss`. 
Yo diria de mergear primero esto, y luego hacer otro PR...más que nada para avanzar.

2022-05-30 17:29 UTC, claudio-uslenghi approved these changes

2022-05-30 17:30 UTC, claudio-uslenghi commented on __tests__/middlewares/constants.js
> +        issuers: [
ok

2022-05-31 21:42 UTC, MatiasOS approved these changes
:+1:

2022-06-01 12:29 UTC, merged