DIDI-902-callbackTask-cronJob
ong-bitcoin-argentina/DIDI-SSI-Server pull request #63
Opened 2021-02-08 20:02 UTC by uquevedoatix

2021-02-09 15:03 UTC, fsawadyatix commented on services/IssuerService.js
> +		throw new Error(err);
es throw err directamente porque si haces new Error estás generando un error nuevo y no es deseable

2021-02-09 15:04 UTC, fsawadyatix commented on jobs/jobs.js
> +exports.permanentJob = () => {
por qué hay constantes de REFILL?

2021-02-09 15:05 UTC, fsawadyatix commented on jobs/jobs.js
> +			for (const callbackTask of callbackTasks) {
creo que deberías procesar de a una, o al menos no todas, sólo una tanda chica, y dejar para otra pasada el resto

2021-02-09 15:06 UTC, fsawadyatix commented on jobs/jobs.js
> +					await IssuerService.callback(callbackUrl, did, token, { status, expireOn, blockHash, messageError });
estaría bueno que haya una especie de análisis de casos sobre tareas a realizar, entonces por modelo de callbackTask te llega tanto la metadata de la tarea como un tag que te indica qué tarea (en este caso hay una sola que es el callback del issuer, pero a futuro podríamos usar esto mismo para otras cosas)

2021-02-11 20:33 UTC, nlaitanatix requested changes

2021-02-11 20:33 UTC, nlaitanatix commented on jobs/delegatesActions.js
> +	CallbackTask.create({ ...dataError, messageError });
```suggestion
	await CallbackTask.create({ ...dataError, messageError });
```

2021-02-11 20:33 UTC, nlaitanatix commented on jobs/delegatesActions.js
> +		CallbackTask.create({ ...data, status: DONE, expireOn, blockHash });
```suggestion
		await CallbackTask.create({ ...data, status: DONE, expireOn, blockHash });
```

2021-02-11 20:33 UTC, nlaitanatix commented on jobs/delegatesActions.js
> +		CallbackTask.create({ ...data, status: REVOKED });
```suggestion
		await CallbackTask.create({ ...data, status: REVOKED });
```

2021-02-11 20:33 UTC, nlaitanatix commented on jobs/jobs.js
> +			for (const callbackTask of callbackTasks) {
Esto en que quedo @uquevedoatix ? lo que podrias hacer es ordenar por fecha creciente poner un limit al find

2021-02-11 20:33 UTC, nlaitanatix commented on jobs/jobs.js
> +exports.permanentJob = () => {
Esto parece de Ronda, fijate de renombrarlas Uri

2021-03-09 17:14 UTC, nlaitanatix approved these changes

2021-03-22 17:29 UTC, merged