Instalar y configurar swagger
ong-bitcoin-argentina/DIDI-SSI-Server pull request #78
Opened 2021-04-19 15:57 UTC by fedelmar

Instalar y configurar swagger para generar documentación de la API.

2021-04-19 16:07 UTC, Diegoro21 submitted a review, later dismissed

2021-04-19 17:26 UTC, MatiasOS requested changes

2021-04-19 17:26 UTC, MatiasOS commented on server.js
> +	  info: {
```
    {
      "title": process.env.NAME,
      "description": `Environment: ${process.env.ENVIRONMENT}`,
      "version": `process.env.VERSION`,
    }
```

2021-04-19 17:26 UTC, MatiasOS commented on server.js
> +	apis: ['./*.js'], // files containing annotations as above
Esto toma solo los archivos **.js** al mismo nivel de **server.js**. Debería incluir también en el array `./routes/*.js`.

2021-04-20 19:56 UTC, MatiasOS requested changes

2021-04-20 19:56 UTC, MatiasOS commented on server.js
> +		"version": `${process.env.VERSION}`,
Acá podés hacer simplemente **"version": process.env.VERSION,**

2021-04-20 22:35 UTC, MatiasOS approved these changes

2021-04-20 22:36 UTC, merged