Documentacion rutas AdminRoutes
ong-bitcoin-argentina/DIDI-SSI-Server pull request #83
Opened 2021-04-28 16:00 UTC by Diegoro21

Documentación en Swagger de las  rutas AdminRoutes.

2021-04-28 16:16 UTC, fedelmar submitted a review, later dismissed

2021-04-28 18:22 UTC, MatiasOS requested changes

2021-04-28 18:22 UTC, MatiasOS commented on routes/AdminRoutes.js
> + *         description: Acción no autorizada
Una respuesta posible es **404: User does not exist**

2021-04-28 18:22 UTC, MatiasOS commented on routes/AdminRoutes.js
> + *         description: Acción no autorizada
Este también puede devolver **404: User does not exist**

2021-04-30 16:15 UTC, MatiasOS approved these changes

2021-04-30 16:16 UTC, merged