Documentacion endpoints IssuerRoutes
ong-bitcoin-argentina/DIDI-SSI-Server pull request #85
Opened 2021-04-28 22:20 UTC by Diegoro21

Documentación endpoints IssuerRoutes en Swagger y eliminación de otros innecesarios.

2021-04-28 23:35 UTC, fedelmar approved these changes, later dismissed

2021-04-29 12:16 UTC, MatiasOS requested changes

2021-04-29 12:16 UTC, MatiasOS commented on routes/IssuerRoutes.js
> + *               issuerDid:
puede ser que **issuerDid** no este en uso?

2021-04-29 13:15 UTC, Diegoro21 commented on routes/IssuerRoutes.js
> + *               issuerDid:
si, fue eliminado.

2021-04-30 12:52 UTC, MatiasOS approved these changes

2021-04-30 12:52 UTC, merged