Document rutas de AppUserAuthRoutes
ong-bitcoin-argentina/DIDI-SSI-Server pull request #88
Opened 2021-04-29 14:45 UTC by fedelmar

Documentación endpoints AppUserAuthRoutes en Swagger

2021-04-29 16:44 UTC, Diegoro21 submitted a review, later dismissed

2021-04-30 13:44 UTC, MatiasOS commented on routes/AppUserAuthRoutes.js
> + *     parameters:
Falta **userJWT** en body

2021-04-30 13:50 UTC, MatiasOS requested changes

2021-04-30 13:50 UTC, MatiasOS commented on routes/AppUserAuthRoutes.js
> + *     summary: Crea una aplicación para volverla autorizada por DIDI
Autoriza una aplicación para sincronizar con DIDI

2021-04-30 13:50 UTC, MatiasOS commented on routes/AppUserAuthRoutes.js
> + *   post:
Falta el header Authorization

2021-04-30 16:20 UTC, MatiasOS requested changes

2021-04-30 16:20 UTC, MatiasOS commented on routes/AppUserAuthRoutes.js
> + *         name: appJWT
Fijate que en la linea 153 lo obtiene como **const appJWT = req.header("Authorization");**. 
Acá hay que poner name: Authorization

2021-04-30 16:45 UTC, MatiasOS approved these changes

2021-04-30 16:45 UTC, merged